module.exports = () => {
    console.log('Options:');
    console.log('\t--help');
    console.log('\t\tShow help');
    console.log('');
    console.log('\t--name * required');
    console.log('\t\tstring');
    console.log('\t\tName of the check');
    console.log('');
    console.log('\t--test_type * required');
    console.log('\t\tenum');
    console.log('\t\t"DNS" "HEAD" "HTTP" "PING" "SMTP" "SSH" "TCP"');
    console.log('\t\tUptime check type');
    console.log('');
    console.log('\t--website_url * required');
    console.log('\t\tstring <uri>');
    console.log('\t\tURL or IP address of the server under test');
    console.log('');
    console.log('\t--check_rate * required');
    console.log('\t\tinteger <int32>');
    console.log('\t\tEnum: 0 30 60 300 900 1800 3600 86400');
    console.log('\t\tNumber of seconds between checks');
    console.log('');
    console.log('\t--basic_username');
    console.log('\t\tstring');
    console.log('\t\tBasic authentication username');
    console.log('');
    console.log('\t--basic_password');
    console.log('\t\tstring');
    console.log('\t\tBasic authentication password');
    console.log('');
    console.log('\t--confirmation');
    console.log('\t\tinteger <int32> [ 0 .. 3 ]');
    console.log('\t\tDefault: 2');
    console.log('\t\tNumber of confirmation servers to confirm downtime before an alert is triggered');
    console.log('');
    console.log('\t--contact_groups');
    console.log('\t\tArray of strings');
    console.log('\t\tList of contact group IDs');
    console.log('');
    console.log('\t--custom_header');
    console.log('\t\tstring');
    console.log('\t\tJSON object. Represents headers to be sent when making requests');
    console.log('');
    console.log('\t--do_not_find');
    console.log('\t\tboolean');
    console.log('\t\tDefault: false');
    console.log('\t\tWhether to consider the check as down if the content is present within the response');
    console.log('');
    console.log('\t--dns_ips');
    console.log('\t\tArray of strings');
    console.log('\t\tList of IP addresses to compare against returned DNS records');
    console.log('');
    console.log('\t--dns_server');
    console.log('\t\tstring');
    console.log('\t\tFQDN or IP address of the nameserver to query');
    console.log('');
    console.log('\t--enable_ssl_alert');
    console.log('\t\tboolean');
    console.log('\t\tDefault: false');
    console.log('\t\tWhether to send an alert if the SSL certificate is soon to expire');
    console.log('');
    console.log('\t--final_endpoint');
    console.log('\t\tstring');
    console.log('\t\tSpecify where the redirect chain should end');
    console.log('');
    console.log('\t--find_string');
    console.log('\t\tstring');
    console.log('\t\tString to look for within the response. Considered down if not found');
    console.log('');
    console.log('\t--follow_redirects');
    console.log('\t\tboolean');
    console.log('\t\tDefault: false');
    console.log('\t\tWhether to follow redirects when testing. Disabled by default');
    console.log('');
    console.log('\t--host');
    console.log('\t\tstring');
    console.log('\t\tName of the hosting provider');
    console.log('');
    console.log('\t--include_header');
    console.log('\t\tboolean');
    console.log('\t\tDefault: false');
    console.log('\t\tInclude header content in string match search');
    console.log('');
    console.log('\t--paused');
    console.log('\t\tboolean');
    console.log('\t\tDefault: false');
    console.log('\t\tWhether the check should be run');
    console.log('');
    console.log('\t--port');
    console.log('\t\tinteger <int32> >= 0');
    console.log('\t\tDestination port for TCP checks');
    console.log('');
    console.log('\t--post_body');
    console.log('\t\tstring');
    console.log('\t\tJSON object. Payload submitted with the request. Setting this updates the check to use the HTTP POST verb');
    console.log('');
    console.log('\t--post_raw');
    console.log('\t\tstring');
    console.log('\t\tRaw HTTP POST string to send to the server');
    console.log('');
    console.log('\t--regions');
    console.log('\t\tArray of strings');
    console.log('\t\tList of regions on which to run checks. The values required for this parameter can be retrieved from the GET /v1/uptime-locations endpoint.');
    console.log('');
    console.log('\t--status_codes_csv');
    console.log('\t\tstring');
    console.log('\t\tComma separated list of status codes that trigger an alert');
    console.log('');
    console.log('\t--tags');
    console.log('\t\tArray of strings');
    console.log('\t\tList of tags');
    console.log('');
    console.log('\t--timeout');
    console.log('\t\tinteger <int32> [ 5 .. 75 ]');
    console.log('\t\tDefault: 15');
    console.log('\t\tThe number of seconds to wait to receive the first byte');
    console.log('');
    console.log('\t--trigger_rate');
    console.log('\t\tinteger <int32> [ 0 .. 60 ]');
    console.log('\t\tDefault: 0');
    console.log('\t\tThe number of minutes to wait before sending an alert');
    console.log('');
    console.log('\t--use_jar');
    console.log('\t\tboolean');
    console.log('\t\tDefault: false');
    console.log('\t\tWhether to enable cookie storage');
    console.log('');
    console.log('\t--user_agent');
    console.log('\t\tstring');
    console.log('\t\tCustom user agent string set when testing');
}
